version: "3.7"

services:
  node-red:
    image: nodered/node-red:latest
    environment:
      - TZ=Asia/Tokyo
    ports:
      - "1880:1880"
    networks:
      - node-red-net
    volumes:
      - node-red-data:/data
    env_file:
      - .env

volumes:
  node-red-data:

networks:
  node-red-net:
